#############################################################
##### START - INPUT #####
#############################################################

blueprint:
  name: ESP32-korvo micarray Configuration
  description: >
    Integration esp32-korvo
    ℹ️ Version: v1.0
  source_url: https://github.com/haade-administrator/korvo-esphome/blob/dev/esp32korvo_blueprint.yaml
  domain: automation
  homeassistant:
    min_version: 2023.9.0

# yamllint disable rule:line-length
  input:
    ##### MAIN NAME #####
          esp32korvo_name:
            name: ESP32korvo device (REQUIRED)
            description: >
              *SYSTEM settings*
              *Please select the ESPHome device related to the NSPanel to be controlled by this automation*
            default: []
            selector:
              device:
                filter:
                  - integration: esphome
                    model: esp-wrover-kit
                multiple: false
